version: '3.1'

services:
  otusdb:
    image: mysql:8.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: 
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
      - ./data:/data
    ports:
      - "3306:3306"

volumes:
  data: