DELIMITER //

CREATE PROCEDURE generate_sales_data()
BEGIN

    START TRANSACTION;

    DELETE FROM sales WHERE sale_id > 0;
    DELETE FROM stores WHERE store_id > 0;
    ALTER TABLE stores AUTO_INCREMENT = 1;
    ALTER TABLE sales AUTO_INCREMENT = 1;

    INSERT INTO stores (address) VALUES 
    ('Address 1'), ('Address 2'), ('Address 3'), ('Address 4'), ('Address 5'),
    ('Address 6'), ('Address 7'), ('Address 8'), ('Address 9'), ('Address 10');

    INSERT INTO sales (store_id, date, sale_amount)
    SELECT 
        CASE WHEN RAND() <= 0.73 THEN 1 ELSE FLOOR(1 + RAND() * 10) END as store_id,
        TIMESTAMPADD(SECOND, FLOOR(RAND() * 63072000), NOW() - INTERVAL 2 YEAR) as date,
        ROUND(10.00 + (RAND() * 990.00), 2) as sale_amount        
    FROM 
        (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
         UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) a,
        (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
         UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) b,
        (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
         UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) c,
        (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
         UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) d,
        (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
         UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) e
    LIMIT 100000;

    COMMIT;
    
    SELECT CONCAT('Генерация данных завершена. Всего продаж: ', (SELECT COUNT(*) FROM sales)) as status;
END //

DELIMITER ;