CREATE USER 'dba'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'dbapassword';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, 
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, 
      LOCK TABLES, EXECUTE, REPLICATION CLIENT, REPLICATION SLAVE, 
      CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER 
      ON *.* TO 'dba'@'%';